# Generated by Django 4.2.11 on 2024-06-17 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="proce",
            new_name="price",
        ),
    ]
